Webhook: Payment method revoked by customer
BoltApp/braintree-go pull request #7
Opened 2021-03-05 17:16 UTC by fredw

This PR introduces the missing notification type: [the payment method revoked by customer](https://developers.braintreepayments.com/reference/general/webhooks/payment-method/ruby#notification-type-payment_method_revoked_by_customer).
This notification kind is already implemented in other Braintree official SDK, for instance, the [Java SDK](https://github.com/braintree/braintree_java/blob/92543816fbcb8ed69c46502c43b9f7552d34c7ef/src/main/java/com/braintreegateway/WebhookNotification.java#L40).

2021-03-05 17:22 UTC, fredw commented
Could you guys please review this PR? @nirajjayant @leighmcculloch
Thanks!

2021-03-31 00:21 UTC, kenbolt requested changes

2021-03-31 00:21 UTC, kenbolt commented on webhook_notification.go
> +	PaypalAccount             *PayPalAccount             `xml:"paypal-account"`
Shouldn't that be

```suggestion
	PaypalAccount             *PayPalAccount             `xml:"paypal-account,omitempty"`
```

2021-03-31 09:12 UTC, fredw commented on webhook_notification.go
> +	PaypalAccount             *PayPalAccount             `xml:"paypal-account"`
You are right, fixed. Thanks!

2024-05-15 07:17 UTC, closed without merging